services:
  qdeb-app:
    build: .
    ports:
      - "4232:4232"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - postgres
    networks:
      - qdeb-network
      - tabbycat_default

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: qdeb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: csgolox13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qdeb-network

networks:
  qdeb-network:
    driver: bridge
  tabbycat_default:
    external: true

volumes:
  postgres_data:
  uploads_data: